Android: setConnectTimeout to 10 seconds (Samsung A70 Fix)
We had a user with a Samsung Galaxy A70 report download failures
with the stacktrace:

java.net.ConnectException: Failed to connect to <HOSTNAME>/<SERVER-IP>:443
at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:1409)
at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:1359)
at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:221)

A workaround has been suggested here:

https://www.softax.pl/blog/solved-samsung-a70-problems-after-upgrade-to-android-10-do-i-have-to-wait-for-samsung-to-help-my-app-users/

In case the above link breaks, here's some details:

The timeout set by HttpURLConnection.setConnectTimeout it gets passed to libcore.
In the method 'connectErrno' if timeout is positive it will prevent calling connect(2)
directly. See here:

https://android.googlesource.com/platform/libcore/+/refs/heads/android10-c2f2-release/luni/src/main/java/libcore/io/IoBridge.java#156

I've not been able to verify that this works as I don't have the device.